### ISSUE TITLE
Cannot read property '__reactAutoBindMap'

### ISSUE THREAD

**Issue by rogoit** [scotch-io/react-tweets#19]
Everything works fine. But there will not be the notification bar

Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefinedReactClass.createClass.Constructor @ bundle.js:61321../components/TweetsApp.react @ bundle.js:12s @ bundle.js:1e @ bundle.js:1(anonymous function) @ bundle.js:1

**Comment by rlau1115** [comment]
Also getting this issue.

**Comment by zakkzhang** [comment]
+1

**Comment by zakkzhang** [comment]
solved, update react, react-dom and reactify to lastest
